feat(postcard route/controller): create and test
jesscxu/postcard-create pull request #2
Opened 2017-05-08 20:27 UTC by jesscxu

What: created the routes and the controllers to create and submit a postcard

Why: to create a postcard

2017-05-08 20:45 UTC, itsachen requested changes
Just a minor issue and some nits

2017-05-08 20:45 UTC, itsachen commented on app/create/controller.js
> +    $scope.payload = { mail_type: 'usps_first_class' };
You may want to define this outside the scope of `$scope.create`. `views/create.html` refers to `payload` so it should be initialized along with the other scope variables (`loading`, `error`)

2017-05-08 20:45 UTC, itsachen commented on app/create/index.js
> +var Angular = require('angular');
Nit: Newline between 3rd party libraries and internal modules

2017-05-08 20:45 UTC, itsachen commented on app/create/index.js
> +var State = require('./state');
Nit: Align `=`'s

2017-05-08 20:51 UTC, jesscxu commented on app/create/controller.js
> +    $scope.payload = { mail_type: 'usps_first_class' };
But shouldn't the feature flag for payload only be set when the postcard is being created?

2017-06-15 17:40 UTC, robinjoseph08 approved these changes
LGTM!

2017-06-15 17:40 UTC, merged